[package]
name = "x86_inter"
version = "0.1.0"
authors = ["hGriff0n <ghooper96@gmail.com>"]

[dependencies]
nom = "3.1.0"
bit-vec = "0.4.4"
libc = "0.2.24"

[lib]
name = "x86_interpreter"
crate-type = ["staticlib"]